### PR TITLE
Corrected directory behavior, doubled slashes

### PR DESCRIPTION
**Pull request by LaSchmu**
I had following problem:

Using the giiant generator to create a module but had several errors with the route creation, figured it our here. :-)

### CODE REVIEW

**Comment by akaSStalkALEX** [comment]
I faced the same problem. Please have a look at this PR, it's been one month already. In phundament app it causes "page not found" in prototype module when you press button less or html manage in admin panel.

**Comment by schmunk42** [comment]
Sorry, I needed a while to realize the problem :)

Could you double-check my solution, I also added some very basic unit tests.

**Comment by akaSStalkALEX** [comment]
Yep, it's working. Thanks:)

**Comment by akaSStalkALEX** [comment]
Sorry this is off topic, I am not sure where I can ask.  Could you give a hint where I can enable DbAssets exactly I tried your example from documentation, created main less, but I can't see it anywhere in FS, I think it should be enabled somehow.

**Comment by schmunk42** [comment]
We've created a separate extension for this https://github.com/dmstr/yii2-prototype-module

I just saw you've found it already, I'll add some docs there...

**Pull request closed without merging**
